[theme]
name = "Dracula"

[theme.base]
white = "#F8F8F2"
black = "#21222C"
grey = "#3E4451"
blue = "#BD93F9"
red = "#FF5555"
yellow = "#F1FA8C"
orange = "#FFB86C"
green = "#50FA7B"
purple = "#BD93F9"
cyan = "#8BE9FD"
magenta = "#FF79C6"

[theme.syntax]
attribute = "$yellow"
builtinType = "$cyan"
comment = "#6272A4"
constant = "$yellow"
constructor = "$yellow"
embedded = "$cyan"
enum = "$yellow"
enum-member = "$red"
enumMember = "$red"
escape = "$cyan"
field = "$red"
function = "$blue"
"function.method" = "$blue"
interface = "$yellow"
keyword = "$purple"
"keyword.control" = "$purple"
method = "$blue"
number = "$yellow"
property = "$red"
selfKeyword = "$purple"
string = "$green"
struct = "$yellow"
structure = "$yellow"
symbol = "$yellow"
type = "$yellow"
"type.builtin" = "$cyan"
typeAlias = "$yellow"
"variable.other.member" = "$red"

[theme.ui]
"activity.background" = "#282A36"
"activity.current" = "$black"
"completion.background" = "#282A36"
"completion.current" = "#2C313A"
"editor.background" = "$black"
"editor.caret" = "#528bFF"
"editor.current_line" = "#2C313C"
"editor.dim" = "#5C6370"
"editor.focus" = "#CCCCCC"
"editor.foreground" = "$white"
"editor.link" = "$blue"
"editor.selection" = "$grey"
"error_lens.error.background" = "#E06C7520"
"error_lens.error.foreground" = "$red"
"error_lens.other.background" = "#5C637020"
"error_lens.other.foreground" = "#5C6370"
"error_lens.warning.background" = "#E5C07B20"
"error_lens.warning.foreground" = "$yellow"
"hover.background" = "#21252B"
"inlay_hint.background" = "#528bFF88"
"inlay_hint.foreground" = "$white"
"lapce.active_tab" = "#528BFF"
"lapce.border" = "#000000"
"lapce.dropdown_shadow" = "#000000"
"lapce.error" = "$red"
"lapce.inactive_tab" = "#5C6370"
"lapce.scroll_bar" = "$grey"
"lapce.warn" = "$yellow"
"markdown.blockquote" = "#898989"
"palette.background" = "#21252B"
"palette.current" = "#2C313A"
"panel.background" = "#21252B"
"panel.current" = "#2C313A"
"panel.hovered" = "#343A45"
"source_control.added" = "#50A14F32"
"source_control.modified" = "#0184BC32"
"source_control.removed" = "#FF526632"
"status.background" = "#21252B"
"status.modal.insert" = "$red"
"status.modal.normal" = "$blue"
"status.modal.terminal" = "$purple"
"status.modal.visual" = "$yellow"
"terminal.background" = "$black"
"terminal.black" = "$black"
"terminal.blue" = "$blue"
"terminal.bright_black" = "#545862"
"terminal.bright_blue" = "$blue"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_green" = "$green"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_red" = "$red"
"terminal.bright_white" = "#C8CCD4"
"terminal.bright_yellow" = "$yellow"
"terminal.cursor" = "$white"
"terminal.cyan" = "$cyan"
"terminal.foreground" = "$white"
"terminal.green" = "$green"
"terminal.magenta" = "$magenta"
"terminal.red" = "$red"
"terminal.white" = "$white"
"terminal.yellow" = "$yellow"

[ui]
font-family = ""
font-size = 13
header-height = 35
status-height = 25
tab-min-width = 100
scroll-width = 10
drop-shadow-width = 0
preview-editor-width = 0
hover-font-family = ""
hover-font-size = 0
trim-search-results-whitespace = true

